# Generated by Django 5.2.3 on 2026-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_options', '0001_initial'),
        ('voting_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='restaurants',
            field=models.ManyToManyField(blank=True, help_text='Restaurants that participants can vote on in this session', related_name='sessions', to='restaurant_options.restaurant'),
        ),
    ]
