# Generated by Django 5.2.3 on 2026-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price_level', models.CharField(blank=True, choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Upscale'), ('$$$$', 'Luxury')], max_length=4, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('place_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
